#!/bin/bash

cd /home/leslie/keepbuild/projects/food-go

# Direct execution with inline env vars
env \
  FOOD_SERVER_PORT=8080 \
  FOOD_SERVER_READ_TIMEOUT=30s \
  FOOD_SERVER_WRITE_TIMEOUT=30s \
  FOOD_DB_HOST=127.0.0.1 \
  FOOD_DB_PORT=5433 \
  FOOD_DB_USER=food \
  FOOD_DB_PASSWORD=123456 \
  FOOD_DB_NAME=food \
  FOOD_DB_MAX_CONNS=20 \
  FOOD_DB_MIN_CONNS=5 \
  FOOD_LOG_LEVEL=info \
  FOOD_PLATFORM_TANTANTANG_TOKEN=test-token \
  FOOD_PLATFORM_TANTANTANG_SECRET_KEY=test-secret \
  FOOD_PLATFORM_TANTANTANG_BASE_URL=https://test.com \
  FOOD_PLATFORM_DT_TOKEN=test-dt-token \
  FOOD_PLATFORM_XIAOCAN_X_VAYNE=test \
  FOOD_PLATFORM_XIAOCAN_X_TEEMO=test \
  FOOD_PLATFORM_XIAOCAN_X_ASHE=test \
  FOOD_PLATFORM_XIAOCAN_X_NAMI=test \
  FOOD_PLATFORM_XIAOCAN_X_SIVIR=test \
  FOOD_PLATFORM_XIAOCAN_USER_ID=test \
  FOOD_PLATFORM_XIAOCAN_SILK_ID=test \
./bin/main

