// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocked.sql

package db

import (
	"context"
)

const createBlockedProduct = `-- name: CreateBlockedProduct :exec
INSERT OR IGNORE INTO blocked_product (activity_id, user_id)
VALUES (?, ?)
`

type CreateBlockedProductParams struct {
	ActivityID string `json:"activity_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) CreateBlockedProduct(ctx context.Context, arg CreateBlockedProductParams) error {
	_, err := q.db.ExecContext(ctx, createBlockedProduct, arg.ActivityID, arg.UserID)
	return err
}

const deleteBlockedProduct = `-- name: DeleteBlockedProduct :exec
DELETE FROM blocked_product WHERE activity_id = ? AND user_id = ?
`

type DeleteBlockedProductParams struct {
	ActivityID string `json:"activity_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) DeleteBlockedProduct(ctx context.Context, arg DeleteBlockedProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockedProduct, arg.ActivityID, arg.UserID)
	return err
}

const existsBlockedProduct = `-- name: ExistsBlockedProduct :one
SELECT COUNT(*) > 0 AS is_blocked FROM blocked_product WHERE activity_id = ? AND user_id = ?
`

type ExistsBlockedProductParams struct {
	ActivityID string `json:"activity_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) ExistsBlockedProduct(ctx context.Context, arg ExistsBlockedProductParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsBlockedProduct, arg.ActivityID, arg.UserID)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const getBlockedProduct = `-- name: GetBlockedProduct :one
SELECT activity_id, user_id, create_time FROM blocked_product
WHERE activity_id = ? AND user_id = ?
`

type GetBlockedProductParams struct {
	ActivityID string `json:"activity_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) GetBlockedProduct(ctx context.Context, arg GetBlockedProductParams) (BlockedProduct, error) {
	row := q.db.QueryRowContext(ctx, getBlockedProduct, arg.ActivityID, arg.UserID)
	var i BlockedProduct
	err := row.Scan(&i.ActivityID, &i.UserID, &i.CreateTime)
	return i, err
}

const listAllBlockedProducts = `-- name: ListAllBlockedProducts :many
SELECT activity_id, user_id, create_time FROM blocked_product
`

func (q *Queries) ListAllBlockedProducts(ctx context.Context) ([]BlockedProduct, error) {
	rows, err := q.db.QueryContext(ctx, listAllBlockedProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockedProduct{}
	for rows.Next() {
		var i BlockedProduct
		if err := rows.Scan(&i.ActivityID, &i.UserID, &i.CreateTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedProductsByUser = `-- name: ListBlockedProductsByUser :many
SELECT activity_id FROM blocked_product WHERE user_id = ?
`

func (q *Queries) ListBlockedProductsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedProductsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var activity_id string
		if err := rows.Scan(&activity_id); err != nil {
			return nil, err
		}
		items = append(items, activity_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
