// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candidate.sql

package db

import (
	"context"
	"database/sql"
)

const createCandidate = `-- name: CreateCandidate :exec
INSERT INTO candidate_item (group_key, region, title_votes, total_occurrences, last_price, last_status, first_seen_time, last_seen_time)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCandidateParams struct {
	GroupKey         string          `json:"group_key"`
	Region           string          `json:"region"`
	TitleVotes       string          `json:"title_votes"`
	TotalOccurrences sql.NullInt64   `json:"total_occurrences"`
	LastPrice        sql.NullFloat64 `json:"last_price"`
	LastStatus       sql.NullInt64   `json:"last_status"`
	FirstSeenTime    string          `json:"first_seen_time"`
	LastSeenTime     string          `json:"last_seen_time"`
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) error {
	_, err := q.db.ExecContext(ctx, createCandidate,
		arg.GroupKey,
		arg.Region,
		arg.TitleVotes,
		arg.TotalOccurrences,
		arg.LastPrice,
		arg.LastStatus,
		arg.FirstSeenTime,
		arg.LastSeenTime,
	)
	return err
}

const deleteCandidate = `-- name: DeleteCandidate :exec
DELETE FROM candidate_item WHERE id = ?
`

func (q *Queries) DeleteCandidate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCandidate, id)
	return err
}

const deleteCandidatesByIDs = `-- name: DeleteCandidatesByIDs :exec
DELETE FROM candidate_item WHERE id = ?
`

// Delete multiple candidates by IDs
// Note: IN clause with multiple values handled in Go code
func (q *Queries) DeleteCandidatesByIDs(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCandidatesByIDs, id)
	return err
}

const getCandidateByID = `-- name: GetCandidateByID :one
SELECT id, group_key, region, title_votes, total_occurrences, last_price, last_status, first_seen_time, last_seen_time, create_time, update_time FROM candidate_item
WHERE id = ?
`

func (q *Queries) GetCandidateByID(ctx context.Context, id int64) (CandidateItem, error) {
	row := q.db.QueryRowContext(ctx, getCandidateByID, id)
	var i CandidateItem
	err := row.Scan(
		&i.ID,
		&i.GroupKey,
		&i.Region,
		&i.TitleVotes,
		&i.TotalOccurrences,
		&i.LastPrice,
		&i.LastStatus,
		&i.FirstSeenTime,
		&i.LastSeenTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const listAllCandidates = `-- name: ListAllCandidates :many
SELECT id, group_key, region, title_votes, total_occurrences, last_price, last_status, first_seen_time, last_seen_time, create_time, update_time FROM candidate_item
ORDER BY last_seen_time DESC
`

func (q *Queries) ListAllCandidates(ctx context.Context) ([]CandidateItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CandidateItem{}
	for rows.Next() {
		var i CandidateItem
		if err := rows.Scan(
			&i.ID,
			&i.GroupKey,
			&i.Region,
			&i.TitleVotes,
			&i.TotalOccurrences,
			&i.LastPrice,
			&i.LastStatus,
			&i.FirstSeenTime,
			&i.LastSeenTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidatesByRegion = `-- name: ListCandidatesByRegion :many
SELECT id, group_key, region, title_votes, total_occurrences, last_price, last_status, first_seen_time, last_seen_time, create_time, update_time FROM candidate_item
WHERE region = ?
ORDER BY last_seen_time DESC
`

func (q *Queries) ListCandidatesByRegion(ctx context.Context, region string) ([]CandidateItem, error) {
	rows, err := q.db.QueryContext(ctx, listCandidatesByRegion, region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CandidateItem{}
	for rows.Next() {
		var i CandidateItem
		if err := rows.Scan(
			&i.ID,
			&i.GroupKey,
			&i.Region,
			&i.TitleVotes,
			&i.TotalOccurrences,
			&i.LastPrice,
			&i.LastStatus,
			&i.FirstSeenTime,
			&i.LastSeenTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCandidate = `-- name: UpdateCandidate :exec
UPDATE candidate_item
SET title_votes = ?,
    total_occurrences = ?,
    last_price = ?,
    last_status = ?,
    last_seen_time = ?,
    update_time = datetime('now')
WHERE id = ?
`

type UpdateCandidateParams struct {
	TitleVotes       string          `json:"title_votes"`
	TotalOccurrences sql.NullInt64   `json:"total_occurrences"`
	LastPrice        sql.NullFloat64 `json:"last_price"`
	LastStatus       sql.NullInt64   `json:"last_status"`
	LastSeenTime     string          `json:"last_seen_time"`
	ID               int64           `json:"id"`
}

func (q *Queries) UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) error {
	_, err := q.db.ExecContext(ctx, updateCandidate,
		arg.TitleVotes,
		arg.TotalOccurrences,
		arg.LastPrice,
		arg.LastStatus,
		arg.LastSeenTime,
		arg.ID,
	)
	return err
}
