// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master_product.sql

package db

import (
	"context"
	"database/sql"
)

const createMasterProduct = `-- name: CreateMasterProduct :exec
INSERT INTO master_product (id, region, platform, standard_title, price, status, trust_score)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMasterProductParams struct {
	ID            string          `json:"id"`
	Region        string          `json:"region"`
	Platform      sql.NullString  `json:"platform"`
	StandardTitle string          `json:"standard_title"`
	Price         sql.NullFloat64 `json:"price"`
	Status        sql.NullInt64   `json:"status"`
	TrustScore    sql.NullInt64   `json:"trust_score"`
}

func (q *Queries) CreateMasterProduct(ctx context.Context, arg CreateMasterProductParams) error {
	_, err := q.db.ExecContext(ctx, createMasterProduct,
		arg.ID,
		arg.Region,
		arg.Platform,
		arg.StandardTitle,
		arg.Price,
		arg.Status,
		arg.TrustScore,
	)
	return err
}

const deleteMasterProduct = `-- name: DeleteMasterProduct :exec
DELETE FROM master_product WHERE id = ?
`

func (q *Queries) DeleteMasterProduct(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMasterProduct, id)
	return err
}

const getMasterProductByID = `-- name: GetMasterProductByID :one
SELECT id, region, standard_title, price, status, trust_score, create_time, update_time, platform FROM master_product
WHERE id = ?
`

func (q *Queries) GetMasterProductByID(ctx context.Context, id string) (MasterProduct, error) {
	row := q.db.QueryRowContext(ctx, getMasterProductByID, id)
	var i MasterProduct
	err := row.Scan(
		&i.ID,
		&i.Region,
		&i.StandardTitle,
		&i.Price,
		&i.Status,
		&i.TrustScore,
		&i.CreateTime,
		&i.UpdateTime,
		&i.Platform,
	)
	return i, err
}

const listAllMasterProducts = `-- name: ListAllMasterProducts :many
SELECT id, region, standard_title, price, status, trust_score, create_time, update_time, platform FROM master_product
ORDER BY update_time DESC
`

func (q *Queries) ListAllMasterProducts(ctx context.Context) ([]MasterProduct, error) {
	rows, err := q.db.QueryContext(ctx, listAllMasterProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterProduct{}
	for rows.Next() {
		var i MasterProduct
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.StandardTitle,
			&i.Price,
			&i.Status,
			&i.TrustScore,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterProductsByPlatform = `-- name: ListMasterProductsByPlatform :many
SELECT id, region, standard_title, price, status, trust_score, create_time, update_time, platform FROM master_product
WHERE platform = ?
ORDER BY update_time DESC
`

func (q *Queries) ListMasterProductsByPlatform(ctx context.Context, platform sql.NullString) ([]MasterProduct, error) {
	rows, err := q.db.QueryContext(ctx, listMasterProductsByPlatform, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterProduct{}
	for rows.Next() {
		var i MasterProduct
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.StandardTitle,
			&i.Price,
			&i.Status,
			&i.TrustScore,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterProductsByRegion = `-- name: ListMasterProductsByRegion :many
SELECT id, region, standard_title, price, status, trust_score, create_time, update_time, platform FROM master_product
WHERE region = ?
ORDER BY update_time DESC
`

func (q *Queries) ListMasterProductsByRegion(ctx context.Context, region string) ([]MasterProduct, error) {
	rows, err := q.db.QueryContext(ctx, listMasterProductsByRegion, region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterProduct{}
	for rows.Next() {
		var i MasterProduct
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.StandardTitle,
			&i.Price,
			&i.Status,
			&i.TrustScore,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterProductsByRegionAndPlatform = `-- name: ListMasterProductsByRegionAndPlatform :many
SELECT id, region, standard_title, price, status, trust_score, create_time, update_time, platform FROM master_product
WHERE region = ? AND platform = ?
ORDER BY update_time DESC
`

type ListMasterProductsByRegionAndPlatformParams struct {
	Region   string         `json:"region"`
	Platform sql.NullString `json:"platform"`
}

func (q *Queries) ListMasterProductsByRegionAndPlatform(ctx context.Context, arg ListMasterProductsByRegionAndPlatformParams) ([]MasterProduct, error) {
	rows, err := q.db.QueryContext(ctx, listMasterProductsByRegionAndPlatform, arg.Region, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterProduct{}
	for rows.Next() {
		var i MasterProduct
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.StandardTitle,
			&i.Price,
			&i.Status,
			&i.TrustScore,
			&i.CreateTime,
			&i.UpdateTime,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMasterProduct = `-- name: UpdateMasterProduct :exec
UPDATE master_product
SET price = ?,
    status = ?,
    trust_score = ?,
    update_time = datetime('now')
WHERE id = ?
`

type UpdateMasterProductParams struct {
	Price      sql.NullFloat64 `json:"price"`
	Status     sql.NullInt64   `json:"status"`
	TrustScore sql.NullInt64   `json:"trust_score"`
	ID         string          `json:"id"`
}

func (q *Queries) UpdateMasterProduct(ctx context.Context, arg UpdateMasterProductParams) error {
	_, err := q.db.ExecContext(ctx, updateMasterProduct,
		arg.Price,
		arg.Status,
		arg.TrustScore,
		arg.ID,
	)
	return err
}

const updateMasterProductPlatform = `-- name: UpdateMasterProductPlatform :exec
UPDATE master_product
SET platform = ?,
    update_time = datetime('now')
WHERE id = ?
`

type UpdateMasterProductPlatformParams struct {
	Platform sql.NullString `json:"platform"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateMasterProductPlatform(ctx context.Context, arg UpdateMasterProductPlatformParams) error {
	_, err := q.db.ExecContext(ctx, updateMasterProductPlatform, arg.Platform, arg.ID)
	return err
}
