// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type BlockedProduct struct {
	ActivityID string `json:"activity_id"`
	UserID     string `json:"user_id"`
	CreateTime string `json:"create_time"`
}

type CandidateItem struct {
	ID               int64           `json:"id"`
	GroupKey         string          `json:"group_key"`
	Region           string          `json:"region"`
	TitleVotes       string          `json:"title_votes"`
	TotalOccurrences sql.NullInt64   `json:"total_occurrences"`
	LastPrice        sql.NullFloat64 `json:"last_price"`
	LastStatus       sql.NullInt64   `json:"last_status"`
	FirstSeenTime    string          `json:"first_seen_time"`
	LastSeenTime     string          `json:"last_seen_time"`
	CreateTime       string          `json:"create_time"`
	UpdateTime       string          `json:"update_time"`
}

type MasterProduct struct {
	ID            string          `json:"id"`
	Region        string          `json:"region"`
	StandardTitle string          `json:"standard_title"`
	Price         sql.NullFloat64 `json:"price"`
	Status        sql.NullInt64   `json:"status"`
	TrustScore    sql.NullInt64   `json:"trust_score"`
	CreateTime    string          `json:"create_time"`
	UpdateTime    string          `json:"update_time"`
	Platform      sql.NullString  `json:"platform"`
}

type NotificationConfig struct {
	ActivityID     string         `json:"activity_id"`
	UserID         string         `json:"user_id"`
	TargetPrice    float64        `json:"target_price"`
	LastNotifyTime sql.NullString `json:"last_notify_time"`
	CreateTime     string         `json:"create_time"`
	UpdateTime     string         `json:"update_time"`
}

type Product struct {
	ID                 int64           `json:"id"`
	ActivityID         string          `json:"activity_id"`
	Platform           sql.NullString  `json:"platform"`
	Region             sql.NullString  `json:"region"`
	Title              sql.NullString  `json:"title"`
	ShopName           sql.NullString  `json:"shop_name"`
	OriginalPrice      sql.NullFloat64 `json:"original_price"`
	CurrentPrice       sql.NullFloat64 `json:"current_price"`
	SalesStatus        sql.NullInt64   `json:"sales_status"`
	ActivityCreateTime sql.NullString  `json:"activity_create_time"`
	CreateTime         string          `json:"create_time"`
	UpdateTime         string          `json:"update_time"`
}

type ProductPriceTrend struct {
	ID         int64   `json:"id"`
	ActivityID string  `json:"activity_id"`
	Price      float64 `json:"price"`
	RecordDate string  `json:"record_date"`
	CreateTime string  `json:"create_time"`
}

type SyncStatus struct {
	ID           int64          `json:"id"`
	JobName      string         `json:"job_name"`
	LastRunTime  string         `json:"last_run_time"`
	Status       string         `json:"status"`
	ProductCount sql.NullInt64  `json:"product_count"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type UserSetting struct {
	UserID     string `json:"user_id"`
	BarkKey    string `json:"bark_key"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}
