// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
	"database/sql"
)

const countByPlatform = `-- name: CountByPlatform :one
SELECT COUNT(*) FROM product WHERE platform = ?
`

func (q *Queries) CountByPlatform(ctx context.Context, platform sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByPlatform, platform)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO product (
  activity_id, platform, region, title, shop_name,
  original_price, current_price, sales_status, activity_create_time
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateProductParams struct {
	ActivityID         string          `json:"activity_id"`
	Platform           sql.NullString  `json:"platform"`
	Region             sql.NullString  `json:"region"`
	Title              sql.NullString  `json:"title"`
	ShopName           sql.NullString  `json:"shop_name"`
	OriginalPrice      sql.NullFloat64 `json:"original_price"`
	CurrentPrice       sql.NullFloat64 `json:"current_price"`
	SalesStatus        sql.NullInt64   `json:"sales_status"`
	ActivityCreateTime sql.NullString  `json:"activity_create_time"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ActivityID,
		arg.Platform,
		arg.Region,
		arg.Title,
		arg.ShopName,
		arg.OriginalPrice,
		arg.CurrentPrice,
		arg.SalesStatus,
		arg.ActivityCreateTime,
	)
	return err
}

const deleteByActivityIDs = `-- name: DeleteByActivityIDs :exec
DELETE FROM product WHERE activity_id = ?
`

// Delete multiple products by activity IDs
// Note: IN clause with multiple values handled in Go code
func (q *Queries) DeleteByActivityIDs(ctx context.Context, activityID string) error {
	_, err := q.db.ExecContext(ctx, deleteByActivityIDs, activityID)
	return err
}

const deleteByPlatform = `-- name: DeleteByPlatform :exec
DELETE FROM product WHERE platform = ?
`

func (q *Queries) DeleteByPlatform(ctx context.Context, platform sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteByPlatform, platform)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProductByActivityID = `-- name: GetProductByActivityID :one
SELECT id, activity_id, platform, region, title, shop_name, original_price, current_price, sales_status, activity_create_time, create_time, update_time FROM product
WHERE activity_id = ?
`

func (q *Queries) GetProductByActivityID(ctx context.Context, activityID string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByActivityID, activityID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Platform,
		&i.Region,
		&i.Title,
		&i.ShopName,
		&i.OriginalPrice,
		&i.CurrentPrice,
		&i.SalesStatus,
		&i.ActivityCreateTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, activity_id, platform, region, title, shop_name, original_price, current_price, sales_status, activity_create_time, create_time, update_time FROM product
WHERE
  (? = '' OR platform = ?) AND
  (? = '' OR region = ?) AND
  (? IS NULL OR sales_status = ?) AND
  (? IS NULL OR ? = 0 OR activity_create_time >= datetime('now', '-7 days')) AND
  activity_id NOT IN (SELECT activity_id FROM blocked_product)
ORDER BY activity_create_time DESC
`

type ListProductsParams struct {
	Column1     interface{}    `json:"column_1"`
	Platform    sql.NullString `json:"platform"`
	Column3     interface{}    `json:"column_3"`
	Region      sql.NullString `json:"region"`
	Column5     interface{}    `json:"column_5"`
	SalesStatus sql.NullInt64  `json:"sales_status"`
	Column7     interface{}    `json:"column_7"`
	Column8     interface{}    `json:"column_8"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts,
		arg.Column1,
		arg.Platform,
		arg.Column3,
		arg.Region,
		arg.Column5,
		arg.SalesStatus,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Platform,
			&i.Region,
			&i.Title,
			&i.ShopName,
			&i.OriginalPrice,
			&i.CurrentPrice,
			&i.SalesStatus,
			&i.ActivityCreateTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsWithBlockedStatus = `-- name: ListProductsWithBlockedStatus :many
SELECT p.id, p.activity_id, p.platform, p.region, p.title, p.shop_name, p.original_price, p.current_price, p.sales_status, p.activity_create_time, p.create_time, p.update_time FROM product p
INNER JOIN blocked_product b ON p.activity_id = b.activity_id
ORDER BY p.activity_create_time DESC
`

func (q *Queries) ListProductsWithBlockedStatus(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsWithBlockedStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Platform,
			&i.Region,
			&i.Title,
			&i.ShopName,
			&i.OriginalPrice,
			&i.CurrentPrice,
			&i.SalesStatus,
			&i.ActivityCreateTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET current_price = ?,
    sales_status = ?,
    update_time = datetime('now')
WHERE id = ?
`

type UpdateProductParams struct {
	CurrentPrice sql.NullFloat64 `json:"current_price"`
	SalesStatus  sql.NullInt64   `json:"sales_status"`
	ID           int64           `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct, arg.CurrentPrice, arg.SalesStatus, arg.ID)
	return err
}

const updateProductByActivityID = `-- name: UpdateProductByActivityID :exec
UPDATE product
SET current_price = ?,
    sales_status = ?,
    update_time = datetime('now')
WHERE activity_id = ?
`

type UpdateProductByActivityIDParams struct {
	CurrentPrice sql.NullFloat64 `json:"current_price"`
	SalesStatus  sql.NullInt64   `json:"sales_status"`
	ActivityID   string          `json:"activity_id"`
}

func (q *Queries) UpdateProductByActivityID(ctx context.Context, arg UpdateProductByActivityIDParams) error {
	_, err := q.db.ExecContext(ctx, updateProductByActivityID, arg.CurrentPrice, arg.SalesStatus, arg.ActivityID)
	return err
}
