// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountByPlatform(ctx context.Context, platform sql.NullString) (int64, error)
	CreateBlockedProduct(ctx context.Context, arg CreateBlockedProductParams) error
	CreateCandidate(ctx context.Context, arg CreateCandidateParams) error
	CreateMasterProduct(ctx context.Context, arg CreateMasterProductParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	CreateTrend(ctx context.Context, arg CreateTrendParams) error
	DeleteBlockedProduct(ctx context.Context, arg DeleteBlockedProductParams) error
	// Delete multiple products by activity IDs
	// Note: IN clause with multiple values handled in Go code
	DeleteByActivityIDs(ctx context.Context, activityID string) error
	DeleteByPlatform(ctx context.Context, platform sql.NullString) error
	DeleteCandidate(ctx context.Context, id int64) error
	// Delete multiple candidates by IDs
	// Note: IN clause with multiple values handled in Go code
	DeleteCandidatesByIDs(ctx context.Context, id int64) error
	DeleteMasterProduct(ctx context.Context, id string) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteProduct(ctx context.Context, id int64) error
	// Delete multiple trends by activity IDs
	// Note: IN clause with multiple values handled in Go code
	DeleteTrendsByActivityIDs(ctx context.Context, activityID string) error
	ExistsBlockedProduct(ctx context.Context, arg ExistsBlockedProductParams) (bool, error)
	GetBlockedProduct(ctx context.Context, arg GetBlockedProductParams) (BlockedProduct, error)
	GetCandidateByID(ctx context.Context, id int64) (CandidateItem, error)
	GetMasterProductByID(ctx context.Context, id string) (MasterProduct, error)
	GetNotification(ctx context.Context, arg GetNotificationParams) (NotificationConfig, error)
	GetProductByActivityID(ctx context.Context, activityID string) (Product, error)
	GetTrendByActivityIDAndDate(ctx context.Context, arg GetTrendByActivityIDAndDateParams) (ProductPriceTrend, error)
	GetUserSettings(ctx context.Context, userID string) (UserSetting, error)
	ListAllBlockedProducts(ctx context.Context) ([]BlockedProduct, error)
	ListAllCandidates(ctx context.Context) ([]CandidateItem, error)
	ListAllMasterProducts(ctx context.Context) ([]MasterProduct, error)
	ListAllNotifications(ctx context.Context) ([]NotificationConfig, error)
	ListBlockedProductsByUser(ctx context.Context, userID string) ([]string, error)
	ListCandidatesByRegion(ctx context.Context, region string) ([]CandidateItem, error)
	ListMasterProductsByPlatform(ctx context.Context, platform sql.NullString) ([]MasterProduct, error)
	ListMasterProductsByRegion(ctx context.Context, region string) ([]MasterProduct, error)
	ListMasterProductsByRegionAndPlatform(ctx context.Context, arg ListMasterProductsByRegionAndPlatformParams) ([]MasterProduct, error)
	ListNotificationsByUser(ctx context.Context, userID string) ([]NotificationConfig, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsWithBlockedStatus(ctx context.Context) ([]Product, error)
	ListTrendsByActivityID(ctx context.Context, activityID string) ([]ProductPriceTrend, error)
	UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) error
	UpdateMasterProduct(ctx context.Context, arg UpdateMasterProductParams) error
	UpdateMasterProductPlatform(ctx context.Context, arg UpdateMasterProductPlatformParams) error
	UpdateNotificationNotifyTime(ctx context.Context, arg UpdateNotificationNotifyTimeParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductByActivityID(ctx context.Context, arg UpdateProductByActivityIDParams) error
	UpsertNotification(ctx context.Context, arg UpsertNotificationParams) error
	UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error
}

var _ Querier = (*Queries)(nil)
