// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trend.sql

package db

import (
	"context"
)

const createTrend = `-- name: CreateTrend :exec
INSERT INTO product_price_trend (activity_id, price, record_date)
VALUES (?, ?, ?)
ON CONFLICT (activity_id, record_date) DO UPDATE
SET price = MIN(product_price_trend.price, excluded.price)
`

type CreateTrendParams struct {
	ActivityID string  `json:"activity_id"`
	Price      float64 `json:"price"`
	RecordDate string  `json:"record_date"`
}

func (q *Queries) CreateTrend(ctx context.Context, arg CreateTrendParams) error {
	_, err := q.db.ExecContext(ctx, createTrend, arg.ActivityID, arg.Price, arg.RecordDate)
	return err
}

const deleteTrendsByActivityIDs = `-- name: DeleteTrendsByActivityIDs :exec
DELETE FROM product_price_trend WHERE activity_id = ?
`

// Delete multiple trends by activity IDs
// Note: IN clause with multiple values handled in Go code
func (q *Queries) DeleteTrendsByActivityIDs(ctx context.Context, activityID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrendsByActivityIDs, activityID)
	return err
}

const getTrendByActivityIDAndDate = `-- name: GetTrendByActivityIDAndDate :one
SELECT id, activity_id, price, record_date, create_time FROM product_price_trend
WHERE activity_id = ? AND record_date = ?
`

type GetTrendByActivityIDAndDateParams struct {
	ActivityID string `json:"activity_id"`
	RecordDate string `json:"record_date"`
}

func (q *Queries) GetTrendByActivityIDAndDate(ctx context.Context, arg GetTrendByActivityIDAndDateParams) (ProductPriceTrend, error) {
	row := q.db.QueryRowContext(ctx, getTrendByActivityIDAndDate, arg.ActivityID, arg.RecordDate)
	var i ProductPriceTrend
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Price,
		&i.RecordDate,
		&i.CreateTime,
	)
	return i, err
}

const listTrendsByActivityID = `-- name: ListTrendsByActivityID :many
SELECT id, activity_id, price, record_date, create_time FROM product_price_trend
WHERE activity_id = ?
ORDER BY record_date ASC
`

func (q *Queries) ListTrendsByActivityID(ctx context.Context, activityID string) ([]ProductPriceTrend, error) {
	rows, err := q.db.QueryContext(ctx, listTrendsByActivityID, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductPriceTrend{}
	for rows.Next() {
		var i ProductPriceTrend
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.Price,
			&i.RecordDate,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
