// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package db

import (
	"context"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, bark_key, create_time, update_time FROM user_settings WHERE user_id = ?
`

func (q *Queries) GetUserSettings(ctx context.Context, userID string) (UserSetting, error) {
	row := q.db.QueryRowContext(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.BarkKey,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO user_settings (user_id, bark_key)
VALUES (?, ?)
ON CONFLICT (user_id) DO UPDATE
SET bark_key = excluded.bark_key,
    update_time = datetime('now')
`

type UpsertUserSettingsParams struct {
	UserID  string `json:"user_id"`
	BarkKey string `json:"bark_key"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSettings, arg.UserID, arg.BarkKey)
	return err
}
